### ISSUE TITLE
Error when running multiple temperatures for adiabatic flame simulation 

### ISSUE THREAD

**Issue by ajuluc** [ischoegl/ctwrap#4]
So I have an n-decane input model built from RMG and I converted to `.cti` format using cantera 2.4.0 on a Linux system. The file contains 283 species and 8753 reactions. Now I was trying to parallelise the flame simulation code for 4 different temperatures and phi values so that I can save time and memory. This entailed using the `.yaml` format given in the instructions of the ctwrap repository. However, when running this simulation on an interactive node on SLURM high-performance computing, the time it takes for the simulation to finish exceeds the time I have been allocated. Here is the `.cti` file as well as the jupyter notebook and the `.yaml` file. 
[adiabatic_flame_nc10.yaml](https://github.com/ischoegl/ctwrap/files/3794338/adiabatic_flame_nc10.yaml.txt)

[Flame_Speed_Convergence_RMG_nc10_detailed_model_ctwrap.ipynb](https://github.com/ischoegl/ctwrap/files/3794364/Flame_Speed_Convergence_RMG_nc10_detailed_model_ctwrap.ipynb.txt)

[reduced_283.cti](https://github.com/ischoegl/ctwrap/files/3794380/reduced_283.cti.txt)

**Comment by ischoegl** [comment]
Thanks. The issue was that you had it set up for a variation of a large number of equivalence ratios, where some settings have poor convergence. 

The `default` field specifies scalar inputs, whereas `variation` selects the entry that is varied; in your case:
```yaml
# YAML file example for the `adiabatic_flame` module
# file specifes a parameter variation of temperature
variation:
  entry: upstream.T 
  values: [300.0, 360.0, 400.0, 403.0, 470.0, 500.0]
output:
  format: h5
defaults:
  upstream:
    T: [300., kelvin, 'temperature']
    P: [1., atmosphere, 'pressure']
    phi: [1.0, dimensionless, 'equivalence ratio']
    fuel: 'nC10H22(1)'
    oxidizer: 'O2(2):0.21,N2:0.79'
  chemistry:
    mechanism: chem_annotated.cti
  domain:
    width: [30, millimeter, 'domain width']
ctwrap: 0.1.0
```

I'm not familiar with SLURM, but I'd suggest to run a couple of tests on a standard Linux system (or a virtual machine/container, which are easy to set up), so you can troubleshoot prior to releasing jobs that are more difficult to debug on a cluster.
